---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: forbid-new-submodules

    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black

    - repo: local
      hooks:
          - id: pyright
            name: pyright
            entry: pyright
            language: node
            pass_filenames: false
            types: [python]
            additional_dependencies: [pyright@1.1.80]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
